global:
  name: consul
  datacenter: dc1

  tls:
    enabled: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    autoGenerate: true

server:
  replicas: 3
  bootstrapExpect: 3

connectInject:
  enabled: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer

controller:
  enabled: true

meshGateway:
  enabled: true

ui:
 enabled: true
 # Registers a Kubernetes Service for the Consul UI as a LoadBalancer.
 service:
   type: LoadBalancer
